### PR TITLE
Chart.Line  Additional format for the "controlling time interval" prop.   Аllows to set the beginning and end of a range

### PR DESCRIPTION
**Pull request by agav99**
for prop "controlling time interval using object" of Chart.Line  widget  by default the end date of the interval is the current time (Date.now())
Аdded a new format for string type values like "startTimeStamp;endTimeStamp" where startTimeStamp and endTimeStamp are the start and end timestamps of the interval. This can be used to implement zooming and scrolling of the displayed chart data.

### CODE REVIEW

**Comment by Scrounger** [comment]
Thanks for the PR!

Did you test it?
I will do a code review in the next few days

**Comment by agav99** [comment]
//Did you test it?
sure

**Comment by Scrounger** [comment]
Please resolve the conflicts.

**Comment by agav99** [comment]
what is the next step?

**Pull request closed without merging**
